version: '2.2'
services:
 win10:
   build: ./win10_host
   container_name: host_01_win10
   hostname: host_01_win10
   stdin_open: true
   tty: true
   ports:
     - "80"
     - "22"
   networks:
     vulhubnet:
       ipv4_address: 10.1.1.12

networks:
  vulhubnet:
    driver: nat
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1