FROM mcr.microsoft.com/windows/server:ltsc2022
#RUN ["powershell", "Add-WindowsFeature", "AD-Domain-Services"] # Not supported in containers
#RUN ["powershell", "netsh", "interface", "show", "interface"]
#RUN ["netsh", "interface", "ipv4", "set", "dnsservers", "'Wi-Fi'", "static", "8.8.8.8", "primary"]
# RUN ["powershell", "Add-KdsRootKey", "–EffectiveTime", "((get-date).addhours(-1000))"]"
# RUN ["powershell", "Get-KdsRootKey"]
# RUN ["powershell", "New-ADServiceAccount", "-Name", "gmsa1", "-DNSHostName", "c1.example.com"]
#CMD ["powershell", "New-Item", "c:/test2"]

